### ISSUE TITLE
Log-in issue with react-redirect

### ISSUE THREAD

**Issue by codemyjourney** [Inter-Camp/InterCamp#55]
When you sign in to the app, it redirects you to the user page after few seconds.
However, you get to the main page for few seconds.
Seems like it shouldn't be that way.
The idea is to make it seamless and add a loader while the app processes the redirect.

<img width="582" alt="Screen Shot 2021-04-08 at 4 18 50 PM" src="https://user-images.githubusercontent.com/62475313/114091100-3f4d4400-9886-11eb-91bf-4bbeef140cdd.png">

**Comment by golden-on** [comment]
1- after sign in , be redirected to the user page after few seconds
2- create some loading animation that make the user more patient
can you explain more  the process of this feature in steps lik one: two: . . . . ?

**Comment by codemyjourney** [comment]
Hello!
Seems like you understood the problem.
1- after sign in , be redirected to the user page after few seconds
2- while redirecting create some loading animation 

I think the best would be to create some kind of state in redux, where you would store the loading state and then show the loader when the state is 'true'

**Comment by golden-on** [comment]
ok thank you for explanation 
I will make this work fast as possible 
but the last question why we need to use redux for this small task while we can use just a simple state or context?

**Comment by codemyjourney** [comment]
We can use redux state to make it global and also use it for other pages that’d need some loading in the future.

Best regards,
Stacy

On Apr 11, 2021, at 7:37 PM, golden-on ***@***.***> wrote:

﻿

ok thank you for explanation
I will make this work fast as possible
but the last question why we need to use redux for this small task while we can use just a simple state or context?

**Comment by codemyjourney** [comment]
resolved
