### ISSUE TITLE
Move from CRA to NextJs

### ISSUE THREAD

**Issue by enyelsequeira** [Inter-Camp/InterCamp#60]
Hey,

1. CodeMyJourney, don't you think this open source project could be upgraded to be using NextJs. CRA it's great for a simple enough project. However, if you want to scale it and have a lot of user it won't be that easy. I think moving to NextJs would be beneficial if you want to scale it and do production-like application.

2. Do you think moving forward you want the contributors to be following the way of writing styles SCSS? I would like to propose the idea of maybe using tailwind as it is easily implemented with any app and can be used in any large project without any drawbacks.

Thank you,
Enyel

**Comment by codemyjourney** [comment]
Hello!
1. Please explain what kind of features Firebase does't support?
2. Might be a good idea if the project gets bigger.

**Comment by enyelsequeira** [comment]
1. I don't get your question.. I mean might be a good idea to migrate the app to use next Js, I wasn't talking about firebase, sorry if there was any confusion.
2. I think moving forward, to better establish a design pattern would make sense, otherwise specify how the styles should be done 

-Enyel s

**Comment by codemyjourney** [comment]
Would you like to restructure the CSS to SCSS properly and establish the design pattern?

**Comment by enyelsequeira** [comment]
With this, do you think the app should be using tailwind? Tailwind is really good and highly customizable and if people were to contribute they could simply follow tailwind patterns. Just a thought, let me know what you think and I can add tailwind to it

**Comment by codemyjourney** [comment]
Don't think we need it at the moment. It uses Material UI already + some custom styles. We'd need to rewrite everything, and it'd be time consuming. I'd focus more on building new features
SCSS sounds great

**Comment by codemyjourney** [comment]
closed
